#!/usr/bin/env bash

set -o errexit

# Download LUX (http://mcmahan.io/lux)
# Includes Munroe color corpus with train/dev/test split
if [ ! -e rugstk ]; then
    echo 'Downloading LUX...'
    curl -O http://paul.rutgers.edu/~bcm84/rugstk_v1.0.tar.gz
    echo 'Extracting...'
    tar xzf rugstk_v1.0.tar.gz
    mv rugstk_v1 rugstk
    rm rugstk_v1.0.tar.gz
fi

# Download TUNA REG corpus (http://www.abdn.ac.uk/ncs/departments/computing-science/corpus-496.php)
if [ ! -e tuna ]; then
    echo 'Downloading TUNA...'
    wget http://www.abdn.ac.uk/ncs/documents/corpus.zip
    echo 'Extracting...'
    unzip corpus.zip
    mv dist tuna
    rm corpus.zip
# tar xzf REG08_TUNA_DATA_2008-03-10.tar.gz REG08_TUNA-AS_TEST-DATA_FULL.tar.gz
# mv REG08_TUNA_DATA_2008-03-10/* tuna/
# mv REG08_TUNA-AS_TEST-DATA_FULL tuna/test
fi

# Download Robert Hawkins' reference game data
if [ ! -e hawkins_data ]; then
    echo 'Downloading Hawkins ref game data...'
    mkdir hawkins_data
    wget https://raw.githubusercontent.com/hawkrobe/reference_games/db7ab78b7c55f146c7e1ebaf3fdc725022c892e4/data/colorReference/clickedObj/colorReferenceClicks.csv
    wget https://raw.githubusercontent.com/hawkrobe/reference_games/db7ab78b7c55f146c7e1ebaf3fdc725022c892e4/data/colorReference/message/colorReferenceMessage.csv
    mv colorReferenceClicks.csv colorReferenceMessage.csv hawkins_data/
fi

echo 'Installing NumPy, SciPy, Cython, and matplotlib (this could take a while)...'
pip install numpy 'cython>=0.21' 'SciPy>=0.9'

echo 'Installing Theano and Lasagne...'
pip install https://github.com/Theano/Theano/archive/master.zip
pip install https://github.com/Lasagne/Lasagne/archive/master.zip

echo 'Installing other Python module dependencies...'
pip install ConfigArgParse 'pyhocon==0.3.18' pypng 'Protobuf>=3.0.0b2' scikit-learn scikit-image matplotlib

if [ ! -e tensorflow ]; then
    echo 'Checking for tensorboard protos...'
    ( python -c 'import tensorflow.core.util.event_pb2' >/dev/null 2>&1 ) || (
        echo "It looks like you don't have TensorFlow installed, so I'm putting a"
        echo "symlink at ./tensorflow/ to just the bare minimum you need. If you"
        echo "decide to install Tensorflow in the future, you can remove it."
        ln -s third-party/tensorflow tensorflow
    )
fi

echo 'Installing testing modules (optional)...'
pip install nose nose-exclude coverage mock
