#!/usr/bin/env bash
mkdir -p arxiv_submission/images

cp -r \
    *.bbl \
    *.cls \
    *.eps \
    *.sty \
    arxiv_submission/
cp images/*.eps \
    images/*.png \
    images/*.pdf \
    arxiv_submission/images/
for pdf in *-eps-converted-to.pdf; do
    cp "$pdf" arxiv_submission/"${pdf/-eps-converted-to/}"
done
for pdf in images/*-eps-converted-to.pdf; do
    base="$(basename "$pdf")"
    cp "$pdf" arxiv_submission/images/"${base/-eps-converted-to/}"
done
for tex in *.tex; do
    perl -pe 's/(^|[^\\])%.*/\1%/' < "$tex" > arxiv_submission/"$tex"
done
cd arxiv_submission
zip -r ../arxiv_submission.zip *
