#!/bin/bash
# This program updates the .json using mongoexport and converts it to csv using the python script
# Requires mongoexport
# Requires a file called "auth" with the user and password separated by a space on the same line.

# terminate if fail
set -e 

OUT="data_input_raw/"

if [[ ! -f mlab_auth ]] ; then
    echo 'File "mlab_auth" not found. An authentication file is required to access the mlab database. If you have no idea what this is, ask Andrew! He knows.'
		echo 'Format the authention file with the user, a space, then the password. E.g. "user password"'
    exit 1
fi

read -p "WARNING: Previous data will be overwritten. Do you wish to continue? (y/n): " CONT

if [ "$CONT" = "y" ]
then 
	echo Downloading files as json
	# read authentication file for mongo
	auth="mlab_auth"
	while read -r user password
	do
		rm *.csv *.json &> /dev/null || # try remove silently
		echo "User: $user"
		echo "Password: $password"
		# get data
		chat="mongoexport -h ds115583.mlab.com:15583 -d heroku_7slvngr1 -c chatmessages -u $user -p $password -o ${OUT}chatmessages.json"
		clicked="mongoexport -h ds115583.mlab.com:15583 -d heroku_7slvngr1 -c clickedobjs -u $user -p $password -o ${OUT}clickedobjs.json"
		eval $chat
		eval $clicked
	done < "$auth"

    bad_pattern='worker \?ID\|A[A-Z0-9]\{13\}'
    echo 'Removing known bad entries:'
    sed -n "/${bad_pattern}/p" "${OUT}chatmessages.json"
    sed -i "/${bad_pattern}/d" "${OUT}chatmessages.json"

	# convert to csv
	echo Converting json to csv
	python jsonToCSV.py
	echo Conversion done

	echo Copying to ../hawkins_data/
	cp ${OUT}*Chinese* ../hawkins_data/
	echo Done

else
	exit 1
fi

